//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSpeech.UIAtoms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSpeech.UIAtoms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;countries&gt;
        ///  &lt;country CountryName=&quot;Afghanistan&quot; CountryCode=&quot;AF&quot; ISDCode=&quot;+93&quot; LocalCode=&quot;&quot; IDDCode=&quot;00&quot; Currency=&quot;&quot; /&gt;
        ///  &lt;country CountryName=&quot;Albania&quot; CountryCode=&quot;AL&quot; ISDCode=&quot;+355&quot; LocalCode=&quot;&quot; IDDCode=&quot;00&quot; Currency=&quot;Lek&quot; /&gt;
        ///  &lt;country CountryName=&quot;Algeria&quot; CountryCode=&quot;AG&quot; ISDCode=&quot;+213&quot; LocalCode=&quot;&quot; IDDCode=&quot;00&quot; Currency=&quot;&quot; /&gt;
        ///  &lt;country CountryName=&quot;Andorra&quot; CountryCode=&quot;AN&quot; ISDCode=&quot;+376&quot; LocalCode=&quot;&quot; IDDCode=&quot;00&quot; Currency=&quot;&quot; /&gt;
        ///  &lt;country CountryName=&quot;Angola&quot; CountryCode=&quot;AO&quot; ISDCode=&quot;+244&quot; L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
    }
}
